### ISSUE TITLE
How to exit IIS process after task has run?

### ISSUE THREAD

**Issue by cervengoc** [mitchwinn/gulp-serve-iis-express#1]
Hello, first of all thank you for this, I was having a look at the original `gulp-iis-express` plugin and found it very confusing, no documentation at all, etc.

I'm looking for a way to ensure that the started IIS Express process exits when the gulp task has been run which has started it.

**Comment by mitchwinn** [comment]
Hello @cervengoc, are you asking how do you stop the running iis-express gulp task? Currently the only way to stop the gulp task using iis-express is by hitting ctrl+c.

**Comment by cervengoc** [comment]
Thanks for the answer, sorry for the late response. I ended up starting my own process with `gulp-exec`, it gave me a bigger flexibility in my current scenario.
